[package]
name = "map-arduino"
version = "0.1.2"
edition = "2024"
description = "Adds functions to remap an number from one range to another, similar to the one you get in Arduino."
license = " LGPL-3.0-or-later"
readme = "README.md"
repository = "https://crates.io/crates/map-arduino/0.1.1/code/src/lib.rs"

[lib]
name = "map_arduino"
path = "src/lib.rs"

[dependencies]
